version: "3.9"

services:
  app:
    build: .
    container_name: rrag_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: rrag_mongo
    ports:
      - "27017:27017"